apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  EUREKA_SERVER_ADDRESS: "http://eureka-0.eureka:8761/eureka"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  CONFIG_SERVER_URL: "http://config-server-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-cm
data:
  hostname: "postgresql-0.postgresql"
  
