apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  CONFIG_SERVER_URL: "http://config-server-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-cm
data:
  hostname: "postgresql-0.postgresql"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  postgresUser: postgresql
  postgresPassword: password
  postgresDatabase: userdb 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE role (
        id serial PRIMARY KEY,
        name VARCHAR(100) NOT NULL
    );

    INSERT INTO role (name) VALUES ('ROLE_ADMIN');
    INSERT INTO role (name) VALUES ('ROLE_USER');  