apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/c/temp/testfiles"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:10.1
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRESQL_ROOT_PASSWORD
          value: Ghostblade123!
        volumeMounts:
        - name: postgresql-initdb 
          mountPath: /docker-entrypoint-initdb.d
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name:  postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: postgresql-initdb   
          configMap:
            name: postgresql-initdb-cm 


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-cm
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS userdb;
    CREATE DATABASE IF NOT EXISTS eventsdb;
    CREATE DATABASE IF NOT EXISTS notificationdb;


---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
  - port: 5432
          
    

